author = 'Gili "OpenBagTwo" Barlev'
baseURL = 'https://openbagtwo.github.io/MarketWatch'
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = 'en-us'
theme = 'Blonde'
title = 'SMBC MarketWatch'

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 3

[params]
# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"
# Dark mode by default : dark
# Light mode by default : light
darkmode = "light"
# Site description
description = "Blonde theme for Hugo."
# The number of articles to be displayed on a single page.
paginator_pages = "5"
# Number of tags to be displayed.
tagsLimit = 20

[params.ad]
# ex. 000000000
adslot = ""
# Google AdSense
# ex. ca-pub-0000000000000000
googleAdSense = ""
postBottom = false
# Placement of ads
postTop = false

[params.post]
# Number of characters in description
description = "130"
# Disable the "NO IMAGE" image.
noimage = true
# Show thumbnails
thumbnail = true
# See the Tailwind CSS documentation to set it up.
# Recommended settings are h-32 to h-48.
# https://tailwindcss.com/docs/height
thumbnail_height = "lg:h-44"
# https://tailwindcss.com/docs/width
thumbnail_width = "lg:w-auto"

[params.widgets]
# Display widgets
display = true
# Order of widgets to display
widgets = ["search", "archive", "category", "tags", "recent"]

[privacy]

[privacy.instagram]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
